name: Build Mini Game Hub

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Set up Gradle 9.2.1
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.2.1'
      - name: Build
        run: gradle clean build --stacktrace
      - name: Upload Mini Game Hub JAR
        uses: actions/upload-artifact@v4
        with:
          name: MiniGameHub-1.21.11
          path: |
            build/libs/minigamehub-*.jar
            !build/libs/*-sources.jar
          if-no-files-found: error
